# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Pydantic v2 schema for the CASCADE annotation format.

Single entry point: `AnnotationBundle`. Everything is reachable from it.

Current schema version is :data:`CURRENT_SCHEMA_VERSION` (see
:mod:`cascade_av.spec.versions` for the full registry).
"""

from cascade_av.spec.schema import (
    Agent,
    AgentAction,
    AgentActionTypePedestrianVocab,
    AgentActionTypeVocab,
    AgentAmountVocab,
    AgentProperty,
    AgentPropertyTypeVocab,
    AgentTypeVocab,
    AnnotationBundle,
    AnnotationStatusVocab,
    Condition,
    ConditionTypeVocab,
    Containment,
    DirectionRelToEgoVocab,
    DrivingJudgmentVocab,
    EgoAction,
    EgoActionTypeVocab,
    EgoPropertyTypeVocab,
    EgoRelativePose,
    EgoVehicle,
    Environment,
    EnvironmentTypeVocab,
    Influence,
    Keypoint,
    LightColorVocab,
    LightShapeVocab,
    LightStateTypeVocab,
    LightStates,
    MotionStateVocab,
    ObjectStateEntry,
    OpenStateVocab,
    PositionRelToEgoVocab,
    QAIssue,
    SignalHead,
    SignalIntentVocab,
    SignalSourceVocab,
    SignalingDetails,
    SignTypeVocab,
    SilAvAnnotation,
    TrafficLight,
    TrafficObject,
    TrafficObjectQuantityVocab,
    TrafficObjectTypeVocab,
    UiConfig,
    VideoMeta,
)
from cascade_av.spec.versions import (
    CURRENT_SCHEMA_VERSION,
    SCHEMA_HISTORY,
    SUPPORTED_SCHEMA_VERSIONS,
    SchemaVersion,
    changelog_for,
    is_known,
)

__all__ = [
    # Top-level container + the typed annotation tree
    "AnnotationBundle",
    "VideoMeta",
    "SilAvAnnotation",
    "EgoVehicle",
    "EgoAction",
    "Agent",
    "AgentAction",
    "AgentProperty",
    "EgoRelativePose",
    "SignalingDetails",
    "Containment",
    "Influence",
    "Keypoint",
    "Environment",
    "Condition",
    "TrafficObject",
    "ObjectStateEntry",
    "TrafficLight",
    "SignalHead",
    "LightStates",
    "QAIssue",
    "UiConfig",
    # Vocabulary classes (single source of truth for known-value strings)
    "AgentActionTypePedestrianVocab",
    "AgentActionTypeVocab",
    "AgentAmountVocab",
    "AgentPropertyTypeVocab",
    "AgentTypeVocab",
    "AnnotationStatusVocab",
    "ConditionTypeVocab",
    "DirectionRelToEgoVocab",
    "DrivingJudgmentVocab",
    "EgoActionTypeVocab",
    "EgoPropertyTypeVocab",
    "EnvironmentTypeVocab",
    "LightColorVocab",
    "LightShapeVocab",
    "LightStateTypeVocab",
    "MotionStateVocab",
    "OpenStateVocab",
    "PositionRelToEgoVocab",
    "SignTypeVocab",
    "SignalIntentVocab",
    "SignalSourceVocab",
    "TrafficObjectQuantityVocab",
    "TrafficObjectTypeVocab",
    # Schema-version registry
    "CURRENT_SCHEMA_VERSION",
    "SCHEMA_HISTORY",
    "SUPPORTED_SCHEMA_VERSIONS",
    "SchemaVersion",
    "changelog_for",
    "is_known",
]
